export const MessageCode = {
  // User
  USER_CREATED: "USER_CREATED",
  USER_ID_REQUIRED: "USER_ID_REQUIRED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_REMOVED: "USER_REMOVED",
  USER_UPDATED: "USER_UPDATED",
  USER_FOUND: "USER_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_MAIL_INVALID: "USER_MAIL_INVALID",
  USER_MAIL_REQUIRED: "USER_MAIL_REQUIRED",
  USER_FIRST_NAME_REQUIRED: "USER_FIRST_NAME_REQUIRED",
  USER_LAST_NAME_REQUIRED: "USER_LAST_NAME_REQUIRED",
  USER_PASSWORD_REQUIRED: "USER_PASSWORD_REQUIRED",

  // Category
  CATEGORY_CREATED: "CATEGORY_CREATED",
  CATEGORY_NAME_REQUIRED: "CATEGORY_NAME_REQUIRED",
  CATEGORY_ALREADY_EXISTS: "CATEGORY_ALREADY_EXISTS",
  CATEGORIES_NOT_FOUND: "CATEGORIES_NOT_FOUND",
  CATEGORIES_FOUND: "CATEGORIES_FOUND",
  CATEGORY_FOUND: "CATEGORY_FOUND",
  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
  CATEGORY_ID_REQUIRED: "CATEGORY_ID_REQUIRED",
  CATEGORY_REMOVED: "CATEGORY_REMOVED",
  CATEGORY_UPDATED: "CATEGORY_UPDATED",

  // Role
  ROLE_CREATED: "ROLE_CREATED",
  ROLE_NAME_REQUIRED: "ROLE_NAME_REQUIRED",
  ROLE_ALREADY_EXISTS: "ROLE_ALREADY_EXISTS",
  ROLES_NOT_FOUND: "ROLES_NOT_FOUND",
  ROLES_FOUND: "ROLES_FOUND",
  ROLE_FOUND: "ROLE_FOUND",
  ROLE_NOT_FOUND: "ROLE_NOT_FOUND",
  ROLE_ID_REQUIRED: "ROLE_ID_REQUIRED",
  ROLE_REMOVED: "ROLE_REMOVED",
  ROLE_UPDATED: "ROLE_UPDATED",

  // Auth
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_REQUIRED: "TOKEN_REQUIRED",
  EMAIL_REQUIRED: "EMAIL_REQUIRED",
  PASSWORD_INVALID: "PASSWORD_INVALID",
  PASSWORD_REQUIRED: "PASSWORD_REQUIRED",
  SUCCESSFUL_SESSION: "SUCCESSFUL_SESSION",
};
