export enum MessageCode {
  USER_CREATED = "USER_CREATED",
  USER_CREATED_ALREADY = "USER_CREATED_ALREADY",
  USER_ID_REQUIRED = "USER_ID_REQUIRED",
  USER_ID_INVALID = "USER_ID_INVALID",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_FOUND = "USER_FOUND",
  USER_MAIL_REQUIRED = "USER_MAIL_REQUIRED",
  USER_MAIL_INVALID = "USER_MAIL_INVALID",
  USER_REMOVED = "USER_REMOVED",
  USER_UPDATED = "USER_UPDATED",

  USER_FIRSTNAME_REQUIRED = "USER_FIRSTNAME_REQUIRED",
  USER_LASTNAME_REQUIRED = "USER_LASTNAME_REQUIRED",
  USER_PASSWORD_REQUIRED = "USER_PASSWORD_REQUIRED",
}
